version: '3'

services:
  python39-slim:
    image: python:3.9-slim
    ports:
      - "8080:8080"
    volumes:
      - ./docker-data/python39-slim:/code
      - ./ops_tools_data_loaders:/code/ops_tools_data_loaders
      - ./requirements.txt:/code/requirements.txt
    environment:
      - ENV_VARIABLE=value
    command: bash -c "apt-get update && apt-get -y install --no-install-recommends gcc libc-dev libffi-dev libmariadb-dev libpcre3-dev mariadb-client && apt-get clean && rm -rf /var/lib/apt/lists/* && /usr/local/bin/python -m pip install --upgrade pip && pip install -r /code/requirements.txt && rm -rf ~/.cache/pip && tail -f /dev/null"
    networks:
      - customer-success-network
    depends_on:
      - mariadb
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "mariadb",
          "-u root",
          "-p your_password"
        ]
      interval: 5s
      timeout: 10s
      retries: 3

  mariadb:
    image: mariadb
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=your_database
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_password
    volumes:
      - ./docker-data/mariadb:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - customer-success-network

networks:
  customer-success-network:
    driver: bridge
